### ISSUE TITLE
Add red case from Short Circuit 2

### ISSUE THREAD

**Issue by MichaelSiddi** [ThaFresh/openJohnny#7]
Hello, thank you for this repo! This is an amazing job!

I would like to ask if you could add the red box to Johnny 5 from Short Circuit 2

![vlcsnap-2021-02-22-11h00m49s287](https://user-images.githubusercontent.com/2010518/108693798-8e216300-74fe-11eb-8a0f-eda81dc7b6e4.png)

Thank you very much!

**Comment by markenglish** [comment]
no probs, theres a toolbox there now. Just download it separately as its not in a release zip yet
